### ISSUE TITLE
<x> element isn’t strictly necessary

### ISSUE THREAD

**Issue by chris-morgan** [jplatte/turbo.fish#2]
You could use `<t><></t>`, put the two colons in `::before` and `::after`, and give them `order: -1` so that they both come before the `<>`.

(Note I used `<>` instead of `&lt;&gt;`, because escaping them isn’t strictly necessary. The title likewise doesn’t need to escape the angle brackets.)

**Comment by jplatte** [comment]
I was originally trying to get it to work without extra tags, but I didn't think about using `order` to move `::after` to the front. I tried `::before::before` but that didn't work :D

I noticed that empty tags were interpreted as not tags before, do you know if this is universally the case? I'd assume it isn't, considering [validator.w3.org](https://validator.w3.org/) complains about it, but then again it also complains about my inventing tags, which I did anyway because neither Chrome nor Firefox seemed to take offense. I will make sure Servo accepts both those hacks before proceeding though ;)

**Comment by chris-morgan** [comment]
HTML parsing is exhaustively defined these days (from the HTML5 spec
onwards): all modern browsers will parse source text identically. Errors
are more or less hints that you probably did something wrong, but all
browsers will handle them in the same way. So itʼs fine to cheat with
the fish in this way. (I believe old browsers will treat the angle
brackets the same way too, but I havenʼt verified this experimentally.)
